/**
 * Created with IntelliJ IDEA.
 * User: Andrew
 * Date: 17/04/12
 * Time: 1:30 PM
 * To change this template use File | Settings | File Templates.
 */

public class TestM4 {

    public static void main(String[] args) {
        EnigmaMachine m4 = EnigmaBuilder.constructM4("6664C");

        m4.setIndicators("AAAAA");

        String plain = "SDKLFJSLDFJKSLDFKJSDFLKJELKSJDFLKSJDLKSDJFLKJSDF";
        String encrypt = "AEOVXIPCPVZUDSMZCIRRPJCDOYSGATOYBBVSCIBGRKMOSOPU";
        String encipher = m4.encipher(plain);
        System.out.println("We have: " + encipher);
        assert (encipher.equals(encrypt));
        m4.setIndicators("AAAAA");
        assert (m4.encipher(encrypt).equals (plain));

        /**************************************************************/

        m4 = EnigmaBuilder.constructM4("1111A");

        m4.setIndicators("AAAZA");
        assert (m4.encipher("A").equals("H"));

        /**************************************************************/

        m4 = EnigmaBuilder.constructM4("4142A");
        m4.setIndicators("AFAFA");
        plain = "JJJJJFEIFKSIIQZZFKEIJNVVCOOW";
        encrypt = "OVGGKNRQKXGTZSJKUILBXUCXRZLU";
        assert (m4.encipher(plain).equals(encrypt));

        /**************************************************************/

        m4 = EnigmaBuilder.constructM4("2178B");
        m4.setIndicators("COMPP");
        plain = "E";//NIGMAENGMAENIGMAENIGMA";
        encrypt = "S";//MCRAHCZHJPNAMVAZWWFKBW";
        String enciphered = m4.encipher(plain);
        System.out.println("Enciphered Text: " + enciphered);
        System.out.println("Indicators are: "+m4.getCurrentIndicators());
        assert (enciphered.equals(encrypt));

        /**************************************************************/

        m4 = EnigmaBuilder.constructM4("1182C");

        plain = "OURFORMOFGOVERNMENTDOESNOTENTERINTORIVALRYWITHTHEINSTITUTIONS" +
                "OFOTHERSOURGOVERNMENTDOESNOTCOPYOURNEIGHBORSBUTISANEXAMPLE" +
                "TOTHEMITISTRUETHATWEARECALLEDADEMOCRACYFORTHEADMINISTRATION" +
                "ISINTHEHANDSOFTHEMANYANDNOTOFTHEFEWBUTWHILETHEREEXISTSEQUAL" +
                "JUSTICETOALLANDALIKEINTHEIRPRIVATEDISPUTESTHECLAIMOFEXCELLENCE" +
                "ISALSORECOGNIZEDANDWHENACITIZENISINANYWAYDISTINGUISHEDHEISPREFERRED" +
                "TOTHEPUBLICSERVICENOTASAMATTEROFPRIVILEGEBUTASTHEREWARDOFMERIT" +
                "NEITHERISPOVERTYANOBSTACLEBUTAMANMAYBENEFITHISCOUNTRYWHATEVER" +
                "THEOBSCURITYOFHISCONDITIONTHEREISNOEXCLUSIVENESSINOURPUBLICLIFE" +
                "ANDINOURPRIVATEBUSINESSWEARENOTSUSPICIOUSOFONEANOTHERNORANGRYWITH" +
                "OURNEIGHBORIFHEDOESWHATHELIKESWEDONOTPUTONSOURLOOKSATHIMWHICHTHOUGH" +
                "HARMLESSARENOTPLEASANTWHILEWEARETHUSUNCONSTRAINEDINOURPRIVATEBUSINESS" +
                "ASPIRITOFREVERENCEPERVADESOURPUBLICACTSWEAREPREVENTEDFROMDOINGWRONG" +
                "BYRESPECTFORTHEAUTHORITIESANDFORTHELAWSHAVINGAPARTICULARREGARDTOTHOSE" +
                "WHICHAREORDAINEDFORTHEPROTECTIONOFTHEINJUREDASWELLASTHOSEUNWRITTENLAWS" +
                "WHICHBRINGUPONTHETRANSGRESSOROFTHEMTHEREPROBATIONOFTHEGENERALSENTIMENT";


        encrypt = "BAZBMJXZYJQDVFIZUVNJMLEOAEQGWJHVBWIABNIYDNNSOQCJMVDZHQLQKZQSPKVGFLXTOEBHDEFJXBBIWUZCMTBHWPVGZGCXEXNQFGMPACXGURVXYVTXGYKEQMXIIVPQWP" +
                "TQLUSJHEDYSQXVMZLBFHFQRUJRJSMIVDEUCLBPWOOXOFYZDQYVVYGMTCNPEVEIQUPQOAIJVSYWBYPQDPJUGKGVTRXNQMZREMXKCZQUGSBECCBIMTXTKQTPERCIWUKRZXJU" +
                "OBUCRIYNMSXADNDPJYESLJVHEWQFQNRLSWQMCEGBACQMDKWVPIEXNKEPFSPOGDNIVSUHGSAWAXVPKLHTSZDXQVCGNVNIHEZOUTXZWMACTIKQARRDNIUHMMIBBEPIAKUTOI" +
                "XSFJLLFGXOAHHPQAJSDWCESPGALKPWMPUPVNWLZDARPTNCWDPZHPLHKHNMFSXSKGHTKRCWEBVTSJAKKAGXJQNALHPVWECFKKYAKATUJPMQHYDYVKHNDFIQKLBNPQJPKAZI" +
                "RHLVOPZYAGMLCPGKCGQBMHZTOIFRQPBPDITQAMIWEBFHQRKZOQHPOPCCYJYFKIMBSFZGLYMECXTIKWIHDWMPCXWDTBBCTCSWNMXHVWGWWKPHPJLSNASLPZYJXRSUVJZMIR" +
                "CFUYNGPRJCWCEJSFDMYHOQYVYFECWUFJXQQRSOQQYQBHCPXDEHAJDKUAPPYTOHQTFTIJVXYSWYQXCTVLUVQZKBWLQNGGFRWEYNHDPWNKHYRLBLBDUWDRVHMSWEIHMBHQQE" +
                "GKMYRSTZSZINLLMOYAVMPSCAQKBZJIHRHGMTOSAIPJWJQVMKDNSNCQUSLHVRSELUYIJSKTEJIYWFCIUOJACSZQNJVSWYKPLYFRKZFESBFXUCQXAVSLTJNPIVINPRMEUOHV" +
                "UEUEWJOSQIIRDQBIRWOSPXOXTRNYCTPZOECZODXYMGBOVEGUQBWTNVGTSEATTABPRZWCQQMRUDUOHWDGURTVGVHISMSQSKZLRESGBTYLYXTGSWYGPOXJQEV";

        m4.setIndicators("NAZIS");
        assert (m4.encipher(plain).equals(encrypt));
        m4.setIndicators("NAZIS");
        assert (m4.encipher(encrypt).equals(plain));

        System.out.println("M4 tests passed. You are Awesome!");
    }

}
